import "./globals.css";
import local from "next/font/local";

const yakh = local({
  src: "../styles/YekanBakh-Regular.ttf",
  preload: true,
  adjustFontFallback: "Times New Roman",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl">
      <body className={yakh.className}>{children}</body>
    </html>
  );
}
